version: '2'
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./.docker-data/postgres:/var/lib/postgresql/data
#      - ./dev_reverie.sql:/docker-entry-point-init.db/reverie.sql
    environment:
      POSTGRES_DB: dev_reverie
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devuser
